### PR TITLE
[FIX] interface-name-prefix failing on interface with number in name

### LINKED ISSUE #139: interface-name-prefix failing on interface named I18n
We have an interface called `I18n`.
`typescript/interface-name-prefix` throws on that interface

it looks like the problem is here:
https://github.com/nzakas/eslint-plugin-typescript/blob/b804a7c/lib/rules/interface-name-prefix.js#L55
```JS
if (first !== "I" || second !== second.toUpperCase()) {
```

as `'1' === '1'.toUpperCase()` if fails.

### PR DESCRIPTION
**Pull request by bradzacher**
Fixes #139

### CODE REVIEW

File: lib/rules/interface-name-prefix.js [hunk 1]
```diff
@@ -43,19 +43,8 @@ module.exports = {
...
-            const second = name.charAt(1);
 
-            if (second === "") {
-                return false;
-            }
-            if (first !== "I" || second !== second.toUpperCase()) {
-                return false;
-            }
-            return true;
+            return !!name.match(/^I[A-Z]/);
```
Comment (macklinu) [inline lib/rules/interface-name-prefix.js]: I like this solution! Could also use [`RegExp.prototype.test()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test), which returns a boolean, instead of having to cast the output of `match()` to a boolean:

```js
/^I[A-Z]/.test(name)
```

Comment (bradzacher) [reply lib/rules/interface-name-prefix.js]: I prefer that!
I always forget regex's have methods..

**Comment by JamesHenry** [comment]
@bradzacher I am very sorry for the long delay in coming back to this, we are going to work out a better maintenance plan for this project

**Comment by bradzacher** [comment]
@JamesHenry happy to help out if you need it.
