### PR TITLE
Fix: fixes missing test cases in no-unused-vars (fixes #65)

### LINKED ISSUE #65: Rule no-unused-vars does not validate ClassExpressions and Inheritance in interfaces
There are a couple of test cases that were missing in this rule. I added some a few days ago, but found new ones (ClassExpressions and inheritance in interfaces with generics). 

As I said before, I will keep improving this rule as I find new test cases...

### PR DESCRIPTION
**Pull request by weirdpattern**
Added few more test cases and refactored the code

### CODE REVIEW

File: lib/rules/no-unused-vars.js [hunk 1]
```diff
@@ -199,43 +247,21 @@ module.exports = {
...
-            ClassDeclaration(node) {
-                markDecoratorsAsUsed(node);
-                markImplementedInterfacesAsUsed(node);
+            TSInterfaceHeritage(node) {
+                markExtendedInterfaceAsUsed(node);
+            },
+
+            Decorator(node) {
+                markDecoratorAsUsed(node);
             },
```
Comment (j-f1) [inline lib/rules/no-unused-vars.js]: Why isn’t this just `Decorator: markDecoratorAsUsed`?

Comment (weirdpattern) [reply lib/rules/no-unused-vars.js]: No reason, it was late last night 😄 
I will update shortly, TSInterfaceHeritage has the same problem...

**Comment by weirdpattern** [comment]
Done!
